---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  affinity:
    # Node affinity rules
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                  - Compute
          weight: 1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                  - Compute
                  - ControlPlane
  podGC:
    strategy: OnPodCompletion
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
  serviceAccountName: {{ include "helm.fullname" $ | quote }}
  ttlStrategy:
    secondsAfterCompletion: 300

  arguments:
    parameters:
      - name: name
        enum:
{{- range $_ := .Values.bindings | default list }}
          - {{ printf "%s-%s" .profileName ( . | toYaml | b64enc | lower | substr 0 7 ) | quote }}
{{- end }}
      - name: enabled
        enum:
          - "false"
          - "true"

  entrypoint: entrypoint
  templates:
    - name: entrypoint
      resource:
        action: patch
        mergeStrategy: merge
        manifest: |
          apiVersion: org.ulagbulag.io/v1alpha1
          kind: SessionBinding
          metadata:
            name: {{ "{{ workflow.parameters.name }}" | quote }}
            namespace: {{ .Release.Namespace | quote }}
          spec:
            enabled: {{ "{{= \"true\" == workflow.parameters.enabled }}" }}
