---
- name: Check whether nerdctl command exists
  stat:
    path: "{{ "{{ bin_dir }}" }}/nerdctl"
  register: nerdctl_file

- name: Install ContainerD | RockyLinux
  when:
    - not nerdctl_file.stat.exists
    - kiss_os_dist in ['rocky']
  package:
    name: containerd.io
    state: present
  ignore_errors: true

- name: Install ContainerD | Ubuntu
  when:
    - not nerdctl_file.stat.exists
    - kiss_os_dist in ['ubuntu']
  package:
    name: containerd
    state: present
  ignore_errors: true

- name: Start ContainerD
  when: not nerdctl_file.stat.exists
  systemd:
    name: containerd.service
    state: started
    daemon_reload: true

- name: Download nerdctl binary
  when: not nerdctl_file.stat.exists
  shell: |
{{- $.Files.Get "assets/patches/43-manual-nerdctl.sh" | trim | nindent 4 }}
  args:
    executable: /bin/bash
