---
- name: Provision Power Planes - IPMI Common
  include_tasks: power-ipmi-common.yaml

- name: Change boot order to Disk-first for next boot
  when: ipmi.stat.exists
  shell: >
    {{ bin_dir }}/nerdctl run --rm --net host
    --device /dev/ipmi0
    --name "kiss-ipmitool"
    "quay.io/ulagbulag/openark-ipmitool:latest"
    chassis bootparam set bootflag force_disk
  ignore_errors: true

- name: Change boot order to Disk-first
  when: ipmi.stat.exists
  shell: >
    {{ bin_dir }}/nerdctl run --rm --net host
    --device /dev/ipmi0
    --name "kiss-ipmitool"
    "quay.io/ulagbulag/openark-ipmitool:latest"
    chassis bootdev disk options=persistent,efiboot
  ignore_errors: true
