---
- name: Provision Power Planes - IPMI Common
  include_tasks: power-ipmi-common.yaml

- name: Change boot order to PxE-first for next boot
  when: ipmi.stat.exists
  shell: >
    {{ "{{ bin_dir }}/nerdctl" }} run --rm --net host
    --device /dev/ipmi0
    --name "kiss-ipmitool"
    {{ include "helm.ipmitool.image" $ | quote }}
    chassis bootparam set bootflag force_pxe

- name: Change boot order to PxE-first
  when: ipmi.stat.exists
  shell: >
    {{ "{{ bin_dir }}/nerdctl" }} run --rm --net host
    --device /dev/ipmi0
    --name "kiss-ipmitool"
    {{ include "helm.ipmitool.image" $ | quote }}
    chassis bootdev pxe options=persistent,efiboot
  ignore_errors: true
