[package]
name = "openark-vine-session-exec"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
std = [
    "futures/std",
    # "k8s-openapi?/std",
    "thiserror/std",
    "tracing?/std",
]

# TLS
tls-aws-lc-rs = ["kube/rustls-tls"]
tls-openssl = ["kube/openssl-tls"]
tls-ring = ["kube/rustls-tls"]

# Tracing
tracing = ["dep:tracing"]

[dependencies]
openark-vine-session-api = { workspace = true }

futures = { workspace = true }
k8s-openapi = { workspace = true, features = ["schemars"] }
kube = { workspace = true, features = ["client", "ws"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true, optional = true }
