---
apiVersion: v1
kind: Secret
metadata:
  name: minio-openark-provisioning
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
stringData:
{{- range $path, $_ := $.Files.Glob "bin/provisioning*.sh" }}
  {{ base $path | quote }}: |
{{- tpl ( $.Files.Get $path ) $ | trim | nindent 4 }}
{{- end }}
