---
## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: {{ has "org.ulagbulag.io/visualization/grafana" .Values.features }}

  ingress:
    ## IngressClassName for Grafana Ingress.
    ## Should be provided if Ingress is enable.
    ##
    ingressClassName: {{ .Values.ingress.domainName | quote }}

    ## Annotations for Grafana Ingress
    ##
    annotations:
      cert-manager.io/cluster-issuer: {{ .Values.ingress.domainName | quote }}
      nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.auth.domainName }}/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.auth.domainName }}/oauth2/start?rd=https://$host$escaped_request_uri"

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    hosts:
      - "grafana.monitoring.{{ .Values.ingress.domainName }}"

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
      - secretName: grafana-general-tls
        hosts:
          - "grafana.monitoring.{{ .Values.ingress.domainName }}"

  ## Grafana's primary configuration
  ## NOTE: values in map will be converted to ini format
  ## ref: http://docs.grafana.org/installation/configuration/
  ##
  grafana.ini:
    # grafana Authentication can be enabled with the following values on grafana.ini
    server:
      # The full public facing url you use in browser, used for redirects and emails
      root_url: "https://grafana.monitoring.{{ .Values.ingress.domainName }}"

## Deploy a Prometheus instance
##
prometheus:
  ## Configuration for Prometheus service
  ##
  service:
    labels:
      {{ index .Values.openark.labels "org.ulagbulag.io/is-external" | quote }}: "true"
      {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:
    ## AdditionalScrapeConfigs allows specifying additional Prometheus scrape configurations. Scrape configurations
    ## are appended to the configurations generated by the Prometheus Operator. Job configurations must have the form
    ## as specified in the official Prometheus documentation:
    ## https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config. As scrape configs are
    ## appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility
    ## to break upgrades of Prometheus. It is advised to review Prometheus release notes to ensure that no incompatible
    ## scrape configs are going to break Prometheus after the upgrade.
    ## AdditionalScrapeConfigs can be defined as a list or as a templated string.
    ##
    ## The scrape configuration example below will find master nodes, provided they have the name .*mst.*, relabel the
    ## port to 2379 and allow etcd scraping provided it is running on all Kubernetes master nodes
    ##
    additionalScrapeConfigs:
{{- if has "nvidia.com/gpu" .Values.features }}
      - job_name: gpu-nvidia-metrics
        scrape_interval: 30s
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - gpu-nvidia
        scheme: http
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_node_name
            action: replace
            target_label: kubernetes_node
        metrics_path: /metrics
{{- end }}
{{- if has "org.ulagbulag.io/cni" .Values.features }}
      - job_name: kubernetes-endpoints
        scrape_interval: 30s
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape
            action: keep
            regex: true
          - source_labels:
              - __address__
              - __meta_kubernetes_service_annotation_prometheus_io_port
            action: replace
            target_label: __address__
            regex: (.+)(?::\d+);(\d+)
            replacement: $1:$2
{{- end }}

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  tolerations:
    - operator: Exists
      effect: NoSchedule
    - key: {{ index .Values.openark.labels "org.ulagbulag.io/bind" | quote }}
      operator: Exists
      effect: NoExecute
    - key: {{ index .Values.openark.labels "org.ulagbulag.io/bind.profile" | quote }}
      operator: Exists
      effect: NoExecute
    - key: {{ index .Values.openark.labels "org.ulagbulag.io/signed-out" | quote }}
      operator: Exists
      effect: NoExecute
