---
affinity:
  # Node affinity rules
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      # KISS normal control plane nodes should be preferred
      - weight: 1
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/kiss-ephemeral-control-plane
              operator: DoesNotExist
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/kiss
              operator: In
              values:
                - ControlPlane

priorityClassName: system-cluster-critical
