---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook-weight: "1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
  - apiGroups: 
      - gateway.networking.k8s.io 
    resources: 
      - grpcroutes
      - httproutes
      - tlsroutes
    verbs: 
      - watch 
      - list
