{{- if .Values.features.ollama.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" ( include "helm.fullname" $ ) "ollama" | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: session
    {{ index .Values.openark.labels "org.ulagbulag.io/bind.mode" }}: ollama
  ports:
    - name: ollama
      port: 11434
      protocol: TCP
{{- end }}
