#cloud-config
version: 1
autoinstall:
  version: 1

  apt:
    fallback: abort
    geoip: true
    preserve_sources_list: false
    mirror-selection:
      primary:
        - country-mirror
  kernel:
{{- if eq "edge" .Values.kiss.os.kernel }}
    flavor: hwe
{{- end }}
  keyboard:
    layout: us
  locale: en_US.UTF-8
  network:
    version: 2
    renderer: NetworkManager
    ethernets:
      alleths:
        match:
          name: en*
        dhcp4: true
  # refresh-installer:
  #   update: true
  shutdown: reboot
  timezone: geoip
  updates: security

  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
      - {{ .Values.kiss.auth.ssh.key.public | quote }}

  user-data:
    disable_root: true
    # package_update: true
    # package_upgrade: true
    users:
{{- range $_ := .Values.addUsers }}
      - name: {{ .name | quote }}
{{- if not ( empty .groups ) }}
        groups: {{ .groups | join ", " | quote }}
{{- end }}
        lock_passwd: {{ .lock_passwd | ne false }}
{{- if not ( empty .passwd ) }}
        passwd: {{ .passwd | quote }}
{{- end }}
        shell: {{ .shell | default "/bin/bash" | quote }}
        ssh_authorized_keys:
          - {{ $.Values.kiss.auth.ssh.key.public | quote }}
{{- if .sudo | default false }}
        sudo: "ALL=(ALL) NOPASSWD: ALL"
{{- end }}
{{- end }}

  storage:
    swap:
      size: 0
    config:
      # Root drive
      - id: disk0
        type: disk
        match:
          # ssd: true
          size: smallest
        ptable: gpt
        grub_device: true
        preserve: false
        wipe: superblock
      # Partition / EFI
      - id: efi_partition
        type: partition
        size: 1G
        device: disk0
        flag: boot
        grub_device: true
        preserve: false
      - id: efi_format
        type: format
        fstype: fat32
        volume: efi_partition
        preserve: false
      - id: efi_mount
        type: mount
        path: /boot/efi
        device: efi_format
      # Partition / Root
      - id: root_partition
        type: partition
        size: -1
        device: disk0
        preserve: false
      - id: root_format
        type: format
        fstype: btrfs
        volume: root_partition
        preserve: false
      - id: root_mount
        type: mount
        path: /
        device: root_format

  early-commands:
    # Installer Network Configuration
    - |
      cat <<EOF >>/etc/systemd/resolved.conf
      [Resolve]
      DNS={{ .Values.cluster.nameservers.loadBalancer.ipv4 | default .Values.cluster.nameservers.incluster.ipv4 }}
      EOF
      systemctl restart systemd-resolved.service
    - |
      mkdir -p /etc/NetworkManager/conf.d/
      cat <<EOF >/etc/NetworkManager/conf.d/99-systemd.conf
      [main]
      dns=default
      rc-manager=resolvconf
      EOF
    - rm -f /etc/netplan/50-cloud-init*
    - |
      cat <<EOF >/etc/netplan/50-cloud-init.yaml
      network:
        version: 2
        renderer: NetworkManager
        ethernets:
          alleths:
            match:
              name: en*
            dhcp4: true
      EOF
    - >
      apt-get update && apt-get install -y network-manager
      && systemctl disable --now systemd-networkd.service systemd-networkd.socket
      && systemctl enable --now NetworkManager.service
      && nmcli connection reload
      && for dev in $(nmcli connection show --active | awk '{print $4}' | grep -P '^en'); do
      nmcli connection down "${dev}" || true
      ; done
    - until netplan apply; do sleep 3; done
    - until curl "http://assets.{{ .Release.Namespace }}.svc.{{ include "helm.clusterDomainName" $ }}"; do netplan apply || true; sleep 30; done
  late-commands:
    # Execute Post-installation Scripts
    - dhcpcd || true # Keep DHCP
    - echo "nameserver {{ $.Values.cluster.nameservers.loadBalancer.ipv4 | default $.Values.cluster.nameservers.incluster.ipv4 }}" >/etc/resolv.conf # Keep DNS
{{- range $path, $_ := $.Files.Glob "assets/patches/*.sh" }}
{{- $filename := base $path }}
    - >
      curl -o "/target/tmp/{{ $filename }}"
      "http://assets.{{ $.Release.Namespace }}.svc.{{ include "helm.clusterDomainName" $ }}/patches/{{ $filename }}"
      && chmod a+x "/target/tmp/{{ $filename }}"
      && curtin in-target --target=/target -- "/tmp/{{ $filename }}"
      && rm -f "/target/tmp/{{ $filename }}"
{{- end }}
