---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm.fullname" $ | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.fullname" $ | quote }}
    namespace: {{ .Release.Namespace | quote }}
