---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
{{- include "helm.selectorLabels" $ | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
