---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
{{- include "helm.selectorLabels" $ | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
