{{- if .Values.apiserver.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "helm.fullname" $ }}-apiserver"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "helm.fullname" $ }}-apiserver"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - org.ulagbulag.io
    resources:
      - sessionbindings
      - sessionprofiles
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "helm.fullname" $ }}-apiserver"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "helm.fullname" $ }}-apiserver"
subjects:
  - kind: ServiceAccount
    name: "{{ include "helm.fullname" $ }}-apiserver"
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}-apiserver"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
rules:
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}-apiserver"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}-apiserver"
subjects:
  - kind: ServiceAccount
    name: "{{ include "helm.fullname" $ }}-apiserver"
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
