---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "helm.fullname" $ }}-handler"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: handler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}-handler"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: handler
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}-handler"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: handler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}-handler"
subjects:
  - kind: ServiceAccount
    name: "{{ include "helm.fullname" $ }}-handler"
    namespace: {{ .Release.Namespace | quote }}
