{{- define "helm.defaultProfileName" -}}
{{- printf "default" }}
{{- end }}

---
apiVersion: org.ulagbulag.io/v1alpha1
kind: SessionProfile
metadata:
  name: {{ include "helm.defaultProfileName" $ | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 4 }}
spec:
{{- $profile := $.Files.Get "profiles/default.yaml" | fromYaml }}
{{- $_ := unset $profile "ananicy" }}
{{- $_ := unset $profile "auth" }}
{{- $_ := unset $profile.features "vm" }}
{{- $_ := unset $profile "fullnameOverride" }}
{{- $_ := unset $profile "greeter" }}
{{- $_ := unset $profile "ingress" }}
{{- $_ := unset $profile "kubevirt" }}
{{- $_ := unset $profile "nameOverride" }}
{{- $_ := unset $profile "node" }}
{{- $_ := unset $profile "openark" }}
{{- $_ := unset $profile.services.notebook "image" }}
{{- $_ := unset $profile.services.novnc "image" }}
{{- $_ := unset $profile.services.x11vnc "image" }}
{{- $_ := unset $profile.session "priorityClassName" }}
{{- $_ := unset $profile.user "kind" }}
{{- $_ := unset $profile.user "name" }}
{{- $_ := unset $profile.user "role" }}
{{- $_ := unset $profile.vm "hostDevices" }}
{{- $_ := unset $profile.vm.windows "virtioContainerDisk" }}
{{- $_ := unset $profile.volumes "hook" }}
{{- $_ := unset $profile.volumes "hostPathPrefix" }}
{{- $profile | toYaml | nindent 2 }}
