{{- define "helm.baseUrl" -}}
{{- printf "sessions.%s" .Values.ingress.domainName }}
{{- end }}

{{- define "helm.ingress.paths" -}}
paths:

{{- /********************************/}}
{{- if and
  .Values.services.notebook.enabled
  ( not ( empty .Values.node.name ) )
}}
  - path: /sessions/notebook/node/{{ .Values.node.name }}
    pathType: ImplementationSpecific
    backend:
      service:
        name: {{ include "helm.fullname" $ | quote }}
        port:
          number: 8888
{{- end }}

{{- /********************************/}}
{{- if and
  .Values.services.novnc.enabled
  ( not ( empty .Values.node.name ) )
}}
  - path: /sessions/vnc/node/{{ .Values.node.name }}
    pathType: ImplementationSpecific
    backend:
      service:
        name: {{ include "helm.fullname" $ | quote }}
        port:
          number: 6080
{{- end }}

{{- end }}

{{- define "helm.ingress.tls" -}}
- secretName: "{{ .Values.ingress.domainName }}-tls"
  hosts:
    - {{ .Values.ingress.domainName | quote }}
{{- end }}

{{- $paths := index ( include "helm.ingress.paths" $ | fromYaml ) "paths" }}
{{- if not ( empty $paths ) }}

{{- if empty .Values.auth.domainName }}
{{- fail "auth.domainName is required to enable ingress" }}
{{- end }}

{{- if empty .Values.ingress.domainName }}
{{- fail "ingress.domainName is required to enable ingress" }}
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.domainName | quote }}
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization, X-Auth-Request-Email, X-Auth-Request-Groups, X-Auth-Request-Preferred-Username
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.auth.domainName }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.auth.domainName }}/oauth2/start?rd=https://$host$escaped_request_uri"
{{- if not ( empty .Values.user.name ) }}
{{- /* TODO: to be implemented! */}}
{{- end }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.domainName | quote }}
  tls:
{{- include "helm.ingress.tls" $ | trim | nindent 4}}
  rules:
    - host: {{ .Values.ingress.domainName | quote }}
      http:
        paths:
{{- $paths | toYaml | nindent 10 }}

{{- end }}
