{{- if or
  .Values.vm.enabled
  ( eq .Values.volumes.home.type "LocalOwned" )
  ( eq .Values.volumes.home.type "LocalShared" )
}}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "helm.localPVCName" $ }}-init"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "{{ include "helm.localPVCName" $ }}-init"
spec:
  backoffLimit: 5
  suspend: false
  ttlSecondsAfterFinished: null
  template:
    metadata:
      labels:
{{- include "helm.labels" $ | nindent 8 }}
        app.kubernetes.io/component: "{{ include "helm.localPVCName" $ }}-init"
    spec:
      affinity:
{{- include "helm.affinity" $ | nindent 8 }}
      containers:
        - name: init-local-pv
          image: "{{ .Values.greeter.image.repo }}:{{ .Values.greeter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.greeter.image.pullPolicy | quote }}
          command:
            - /usr/bin/env
            - /bin/bash
          args:
            - -c
            - |
{{- tpl ( .Files.Get "bin/init_create_storage.sh" ) $ | trim | nindent 14 }}
          env:
{{- if .Values.vm.enabled }}
            - name: TARGET_UID
              value: "107"
            - name: TARGET_GID
              value: "107"
{{- else }}
            - name: TARGET_UID
              value: {{ .Values.session.context.uid | quote }}
            - name: TARGET_GID
              value: {{ .Values.session.context.gid | quote }}
{{- end }}
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
          securityContext:
            privileged: false
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: {{ include "helm.localPVPath" $ | quote }}
          workingDir: {{ include "helm.localPVPath" $ | quote }}
      restartPolicy: OnFailure
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      volumes:
        - name: data
          hostPath:
            path: {{ include "helm.localPVPath" $ | quote }}
            type: DirectoryOrCreate

{{- end }}
