{{/*
Jupyter Notebook Configs
*/}}
{{- define "helm.notebookName" -}}
{{- printf "%s-notebook" ( include "helm.fullname" $ ) }}
{{- end }}

{{- if and
  .Values.services.notebook.enabled
  ( not .Values.vm.enabled )
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.notebookName" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
stringData:
{{- range $path, $_ := $.Files.Glob "notebook/*.py" }}
  {{ base $path | quote }}: |
{{- tpl ( $.Files.Get $path ) $ | trim | nindent 4 }}
{{- end }}

{{- end }}
