---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
{{- if has .Values.user.role ( list "Dev" ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "helm.serviceAccountName" $ }}-dev"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/privileged: "true"
    org.ulagbulag.io/role: dev
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "helm.serviceAccountName" $ }}-dev"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/privileged: "true"
    org.ulagbulag.io/role: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "helm.serviceAccountName" $ }}-dev"
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.serviceAccountName" $ | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
{{- if has .Values.user.role ( list "Dev" "Viewer" ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "helm.serviceAccountName" $ }}-viewer"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/privileged: "false"
    org.ulagbulag.io/role: viewer
rules:
{{- include "helm.viewerRules" $ | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "helm.serviceAccountName" $ }}-viewer"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/privileged: "false"
    org.ulagbulag.io/role: viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "helm.serviceAccountName" $ }}-viewer"
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.serviceAccountName" $ | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
