---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.smartx.ingress.domainName | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  acme:
    privateKeySecretRef:
      name: "{{ .Values.smartx.ingress.domainName }}-cluster-issuer"
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: {{ .Values.smartx.ingress.domainName | quote }}
