{{- /* ConfigMap */}}
{{- define "helm.messengerKafka" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-agent-kafka" ( include "helm.fullname" $ ) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
data:
  wait.sh: |
{{- $.Files.Get "bin/wait-kafka.sh" | trim | nindent 4 }}
{{- end }}

{{- if eq "Kafka" .Values.messenger.kind }}
{{- include "helm.messengerKafka" . }}
{{- end }}
