{{- if eq "Kafka" .Values.messenger.kind }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    strimzi.io/node-pools: enabled
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  kafka:
    version: 3.9.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: "3.9"
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      retention.ms: 7200000 # 2 hour
      segment.bytes: 1073741824
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
  # FIXME: Set node affinity for zookeepers and operator
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: ceph-block
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}
