{{- if .Values.features.openark.vine.enabled }}
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  clusterQueue: {{ .Values.features.openark.vine.clusterQueueName | quote }}
{{- end }}
