---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "helm.fullname" $ }}-github"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
data:
  appID: {{ .Values.github.app.appID | toString | b64enc | quote }}
  installationID: {{ .Values.github.app.installationID | toString | b64enc | quote }}
