---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.domainName | quote }}
  labels:
    {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: homepage
spec:
  ingressClassName: {{ .Values.ingress.domainName | quote }}
  tls:
    - secretName: "{{ .Values.ingress.domainName }}-tls"
      hosts:
        - {{ .Values.ingress.domainName | quote }}
  rules:
    - host: {{ .Values.ingress.domainName | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType | quote }}
            backend:
              service:
                name: {{ include "helm.fullname" $ | quote }}
                port:
                  number: {{ .Values.service.port }}
