---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: homepage
spec:
  type: {{ .Values.service.type | quote }}
  selector:
{{- include "helm.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: homepage
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.service.port }}
