---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - ""
    resources:
      - endpointslices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - org.ulagbulag.io
    resources:
      - httprouteclaims
      - trafficrouterclasses
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm.fullname" $ | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.fullname" $ | quote }}
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - endpointslices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - patch
  - apiGroups:
      - org.ulagbulag.io
    resources:
      - httprouteclaims
      - trafficrouterclasses
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "openark:{{ $.Chart.Name }}:{{ .Release.Namespace }}:{{ include "helm.fullname" $ }}"
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.fullname" $ | quote }}
    namespace: {{ .Release.Namespace | quote }}
