---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-control-planes-default
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
data:
  defaults.yaml: |
    all:
      children:
        kiss_ephemeral_node:
          vars: {}
        kube_control_plane:
        kube_node:
        calico_rr:
          hosts: {}
        etcd:
        k8s_cluster_default:
          vars: {}
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
          vars:
{{- include "helm.kubesprayConfigs" $
  | fromYaml
  | merge ( .Values.kubespray | default dict )
  | toYaml
  | nindent 12
}}
