---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ index .Values.openark.labels "org.ulagbulag.io/is-external" | quote }}: "true"
    {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
{{- include "helm.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: apiserver
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include "configmaps.kiss-config" $ | sha256sum | quote }}
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        {{ index .Values.openark.labels "org.ulagbulag.io/is-external" | quote }}: "true"
        {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 8 }}
        app.kubernetes.io/component: apiserver
    spec:
      affinity:
        nodeAffinity:
          # KISS normal control plane nodes should be preferred
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/kiss-ephemeral-control-plane
                    operator: DoesNotExist
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/kiss
                    operator: In
                    values:
                      - ControlPlane
      priorityClassName: k8s-cluster-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "helm.serviceAccountSystemName" $ }}
      containers:
        - name: apiserver
          image: "{{ .Values.operator.image.repo }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy | quote }}
          command:
            - /usr/bin/env
            - openark-kiss-backend
          env:
            - name: BASE_URL
              value: {{ .Values.apiserver.baseUrl | quote }}
            - name: BIND_ADDR
              value: 0.0.0.0:8000
            - name: CONTROLLER_NAME
              value: {{ .Chart.Name | quote }}
            - name: CONTROLLER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RUST_LOG
              value: INFO
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: "{{ .Values.apiserver.baseUrl }}/ping"
              port: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: "{{ .Values.apiserver.baseUrl }}/health"
              port: http
          resources:
            requests:
              cpu: 30m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ index .Values.openark.labels "org.ulagbulag.io/is-external" | quote }}: "true"
    {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
spec:
  type: LoadBalancer
  selector:
{{- include "helm.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
