---
apiVersion: v1
kind: Secret
metadata:
  name: kiss-config
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
stringData:
  ###########################################################################
  # Bare-metal Box Authentication Configuration
  ###########################################################################
  auth_ssh_key_id_ed25519: {{ .Values.kiss.auth.ssh.key.private | quote }}

  ###########################################################################
  # Bare-metal Box Intel AMT Configuration
  ###########################################################################
  power_intel_amt_username: {{ .Values.kiss.power.intelAmt.username | quote }}
  power_intel_amt_password: {{ .Values.kiss.power.intelAmt.password | quote }}

  ###########################################################################
  # Bare-metal Box IPMI Configuration
  ###########################################################################
  power_ipmi_username: {{ .Values.kiss.power.ipmi.username | quote }}
  power_ipmi_password: {{ .Values.kiss.power.ipmi.password | quote }}

  ###########################################################################
  # Submit Gateway Configuration
  ###########################################################################
  submit_base_url: {{ printf "http://gateway.%s.svc.%s" .Release.Namespace ( include "helm.clusterDomainName" $ ) | quote }}

  ###########################################################################
  # Network Configuration
  ###########################################################################
  network_wireless_wifi_ssid: {{ .Values.network.wireless.wifi.ssid | quote }}
  network_wireless_wifi_key_mgmt: {{ .Values.network.wireless.wifi.key.mgmt | quote }}
  network_wireless_wifi_key_psk: {{ .Values.network.wireless.wifi.key.psk | quote }}
