---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ index .Values.openark.labels "org.ulagbulag.io/is-external" | quote }}: "true"
    {{ index .Values.openark.labels "org.ulagbulag.io/is-private" | quote }}: "true"
{{- include "helm.labels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
spec:
  type: LoadBalancer
  selector:
{{- include "helm.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: apiserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
