{{- if .Values.kueue.enabled }}
{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "Kueue" -}}

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: {{ printf "%s.%s" ( include "helm.kueueClusterNamePrefix" $ ) .name | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector:
{{- $.Values.kueue.namespaceSelector | toYaml | nindent 4 }}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  queueingStrategy: BestEffortFIFO
  resourceGroups:
    # FIXME: to be configured
    - coveredResources:
        - cpu
        - ephemeral-storage
        - memory
        - nvidia.com/gpu
      flavors:
        # default flavor
        - name: {{ printf "%s.%s" ( include "helm.kueueClusterNamePrefix" $ ) .name | quote }}
          resources:
            - name: cpu
              nominalQuota: 1000000 # infinity quotas
            - name: ephemeral-storage
              nominalQuota: 1000000Ti # infinity quotas
            - name: memory
              nominalQuota: 1000000Gi # infinity quotas
            - name: nvidia.com/gpu
              nominalQuota: 1000000 # infinity quotas
        # extra flavors
{{- range $_ := .extraFlavors | default list }}
        -
{{- . | toYaml | nindent 10 }}
{{- end }}
  stopPolicy: None

{{- end }}
{{- end }}
{{- end }}
