{{- if .Values.kueue.enabled }}
{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "Kueue" -}}

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: {{ printf "%s.%s" ( include "helm.fullname" $ ) .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  clusterQueue: {{ printf "%s.%s" ( include "helm.kueueClusterNamePrefix" $ ) .name | quote }}

{{- end }}
{{- end }}
{{- end }}
