---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ include "helm.fullname" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  kafka:
    url: "{{ include "helm.fullname" $ }}-kafka-brokers:9092" # must be managed independently
