---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "{{ include "helm.fullname" $ }}-ci"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  affinity:
    # Node affinity rules
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                  - Compute
          weight: 1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                  - Compute
                  - ControlPlane
  podGC:
    strategy: OnPodCompletion
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
  serviceAccountName: "{{ include "helm.fullname" $ }}-ci"
  ttlStrategy:
    secondsAfterCompletion: 300
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: ceph-block
  volumes:
    - name: secret-argo-ci
      secret:
        secretName: "{{ include "helm.fullname" $ }}-argo-ci"
        defaultMode: 256 # 0o400

  arguments:
    parameters:
      - name: workdir
        value: /workdir

  entrypoint: entrypoint
  templates:
    - name: entrypoint
      dag:
        tasks:
          - name: pull
            template: pull

          - name: ci
            template: execute
            dependencies:
              - pull
            arguments:
              parameters:
                - name: command
                  value: ./hack/git-ci.sh

    - name: execute
      inputs:
        parameters:
          - name: command
      container:
        image: quay.io/ulagbulag/openark:devel
        command:
          - /usr/bin/env
          - {{ "{{ inputs.parameters.command }}" | quote }}
        env:
          - name: COMMIT_SHA
            value: {{ "{{ workflow.parameters.commit_sha }}" | quote }}
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: "{{ include "helm.fullname" $ }}-github"
                key: appID
          - name: GITHUB_INSTALLATION_ID
            valueFrom:
              secretKeyRef:
                name: "{{ include "helm.fullname" $ }}-github"
                key: installationID
          - name: GITHUB_PRIVATE_KEY_PATH
            value: /run/secrets/ulagbulag.io/argo-ci/private-key.pem
          - name: REPO_OWNER
            value: {{ "{{ workflow.parameters.repo_owner }}" | quote }}
          - name: REPO_NAME
            value: {{ "{{ workflow.parameters.repo_name }}" | quote }}
        volumeMounts:
          - name: secret-argo-ci
            mountPath: /run/secrets/ulagbulag.io/argo-ci/private-key.pem
            subPath: private-key.pem
            readOnly: true
          - name: workdir
            mountPath: /home/user
        workingDir: {{ printf "/home/user%s" "{{ workflow.parameters.workdir }}" | quote }}

    - name: pull
      container:
        image: quay.io/ulagbulag/openark:devel
        command:
          - /usr/bin/env
          - bash
        args:
          - -c
          - |
{{- .Files.Get "bin/pull.sh" | trim | nindent 14 }}
        volumeMounts:
          - name: workdir
            mountPath: /home/user
        workingDir: /home/user
