---
defaultProfileName: ""

profiles:
  - kind: Desktop # Options: [Desktop, Notebook, VirtualMachine]
    name: ubuntu-24.04
    session:
      context:
        hostNetwork: true

  - kind: Notebook # Options: [Desktop, Notebook, VirtualMachine]
    name: pytorch
    image:
      repo: nvcr.io/nvidia/pytorch
      tag: 25.02-py3

  - kind: VirtualMachine # Options: [Desktop, Notebook, VirtualMachine]
    name: windows-11
    cdrom:
      filename: Win11_24H2_Korean_x64.iso
    windows:
      eula: false

bindings:
  []
  # - profileName: pytorch
  #   priority: 0 # Default: 0
  #   nodeSelector: {}
  #   user:
  #     kind: Guest # Options: [Guest, User]
  #     name: ""
