# Copyright (c) 2022-2025 Ho Kim (ho.kim@ulagbulag.io). All rights reserved.
# Use of this source code is governed by a GPL-3-style license that can be
# found in the LICENSE file.

# Be ready for serving
FROM "{{ .Values.debian.image.repo }}:{{ .Values.debian.image.tag }}" AS server

# Install dependencies
RUN apt-get update && apt-get install -y \
        ipmitool \
    # Cleanup
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

# Server Configuration
WORKDIR /usr/bin
ENTRYPOINT [ "/usr/bin/ipmitool" ]
CMD [ "" ]
