---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  # NOTE: Fixed webhook name
  name: {{ .Chart.Name | quote }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "helm.fullname" $ }}"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
webhooks:
  - name: "{{ include "helm.fullname" $ }}.{{ .Release.Namespace }}.svc"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: "In"
          values:
            - {{ .Release.Namespace | quote }}
    objectSelector:
      matchLabels:
        app.kubernetes.io/component: nvidia-driver
        nvidia.com/precompiled: "false"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "*"
        resources:
          - pods
        operations:
          - CREATE
        scope: Namespaced
    admissionReviewVersions:
      - v1
    matchPolicy: Equivalent
    timeoutSeconds: 5
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "helm.fullname" $ | quote }}
        namespace: {{ .Release.Namespace | quote }}
        path: /
