---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
