---
image:
  repo: ghcr.io/k8snetworkplumbingwg/multus-cni
  tag: snapshot
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 50Mi
    ephemeral-storage: 200Mi
  requests:
    cpu: 100m
    memory: 50Mi
    ephemeral-storage: 50Mi

securityContext:
  privileged: true
  seccompProfile:
    type: RuntimeDefault

tolerations: []
