---
apiserver:
  baseUrl: /api/v1
  image:
    repo: quay.io/ulagbulag/openark
    tag: ""
    pullPolicy: Always

auth:
  domainName: ""

features:
  vm: false

greeter:
  image:
    repo: quay.io/ulagbulag/openark-vine-greeter
    tag: latest
    pullPolicy: Always

ingress:
  domainName: ""

nodeSelector: {}

openark:
  labels: {}

operator:
  image:
    repo: quay.io/ulagbulag/openark
    tag: ""
    pullPolicy: Always

session:
  defaultNamespace: "" # default: current namespace

smartx:
  repo:
    baseUrl: ""
    owner: ""
    name: ""
    revision: ""

volumes:
  public:
    enabled: true
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: ceph-filesystem

  static:
    enabled: true
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Ti
    storageClassName: ceph-filesystem
