---
debian:
  image:
    repo: ""
    tag: ""

edk2:
  repo:
    baseUrl: https://github.com
    owner: SmartX-Team
    name: edk2
    revision: master

virtLauncher:
  image:
    repo: quay.io/kubevirt/virt-launcher
    tag: ""
