---
agents:
  llm:
    image:
      repo: quay.io/ulagbulag/h2pc-agent-llm
      tag: ""
      pullPolicy: Always
    resources:
      requests:
        cpu: 30m
        memory: 20Mi
      limits:
        cpu: 100m
        memory: 100Mi

dag:
  - name: source-0
    operator: Prompt
    params:
      name: source
    # env: []
    # resources: {}
    # srcs: []
    # sinks:
    #   - kind: Stream # Options: [Stream]

env: []

# extraOperators:
#   - name: hello-world # NOTE: kebab-case, not PascalCase!
#     template: |
#       ---
#       kind: LLM
#       params:
#         - name: modelName
#           type: String
#           default: exaone3.5:32b
#         - name: name
#           type: String
#       env:
#         - name: OPENAI_MODEL_NAME
#           value: {{ .params.modelName | quote }}
#       resources: null
#       srcs: null
#       sinks:
#         - kind: Stream
#       template:
#         - role: user
#           template: Hello {{ .params.name }}!
extraOperators: []

# extraPrompts:
#   - name: my-name-is-gildong-hong
#     template:
#       - role: system
#         template: |
#           Your name is Gildong Hong.
#       - role: user
#         template: |
#           What is your name?
extraPrompts: []

messenger:
  kind: Kafka # Options: [Kafka]
  kafka:
    image:
      repo: docker.io/ubuntu/kafka
      tag: latest
      pullPolicy: Always
