---
daemonset:
  affinity:
    # Node affinity rules
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/kiss
                operator: In
                values:
                  - Compute
          weight: 1

  tolerations: []

image:
  repo: quay.io/ulagbulag/openark
  tag: ""
  pullPolicy: Always

io:
  sources:
    - nvme

  target: nvme
