{{- if .Values.enabled }}
{{- $controllerName := include "helm.componentName" ( dict "root" . "component" "controller" ) }}
{{- $namespaceRoleName := include "helm.componentName" ( dict "root" . "component" "controller-runtime" ) }}
{{- $rookRoleName := include "helm.clusterScopedComponentName" ( dict "root" . "component" "controller-rook" ) }}
{{- $nodeRoleName := include "helm.clusterScopedComponentName" ( dict "root" . "component" "controller-nodes" ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $namespaceRoleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-runtime
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $namespaceRoleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namespaceRoleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $controllerName | quote }}
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $rookRoleName | quote }}
  namespace: {{ .Values.rookNamespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-rook
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ceph.rook.io
    resources:
      - cephclusters
    resourceNames:
      - {{ required "cephClusterName is required" .Values.cephClusterName | quote }}
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rookRoleName | quote }}
  namespace: {{ .Values.rookNamespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-rook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rookRoleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $controllerName | quote }}
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $nodeRoleName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-nodes
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $nodeRoleName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $nodeRoleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $controllerName | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
