{{- if .Values.enabled }}
{{- $agentName := include "helm.componentName" ( dict "root" . "component" "agent" ) }}
{{- $controllerName := include "helm.componentName" ( dict "root" . "component" "controller" ) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $agentName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $controllerName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
{{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
{{- end }}
