---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "helm.groupPrefix" $ }}{{ include "helm.fullname" $ }}:dev"
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/privileged: "true"
    org.ulagbulag.io/role: dev
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "helm.groupPrefix" $ }}{{ include "helm.fullname" $ }}:viewer"
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/privileged: "false"
    org.ulagbulag.io/role: viewer
rules:
{{- include "helm.viewerRules" $ | nindent 2 }}
