---
{{- /*
Define ClusterRoles and NamespacedRoles
*/}}
{{- $_ := set $.Values "clusterRoles" ( list "admin" "ops" "viewer" ) }}
{{- $_ := set $.Values "namespacedRoles" ( list "dev" "viewer" ) }}

{{- /*
Create ".Values.roleGroupBindings"
*/}}
{{- $groups := concat ( $.Values.groups | default list ) ( $.Values.extraGroups | default list ) }}
{{- $roles := list "admin" "dev" "sec" "ops" "viewer" }}
{{- $_ := set $.Values "roleGroupBindings" dict }}
{{- range $role := $roles }}
{{- $_ := set $.Values.roleGroupBindings $role list }}
{{- range $group := $groups }}
{{- if eq .role ( $role | title ) }}
{{- $_ := set $.Values.roleGroupBindings $role ( append ( index $.Values.roleGroupBindings $role ) .name | uniq | sortAlpha ) }}
{{- end }}
{{- end }}
{{- end }}

{{- /*
Inherit roles
*/}}
{{- $_ := set $.Values.roleGroupBindings "sec" ( concat $.Values.roleGroupBindings.sec $.Values.roleGroupBindings.admin | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "ops" ( concat $.Values.roleGroupBindings.ops $.Values.roleGroupBindings.admin | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "ops" ( concat $.Values.roleGroupBindings.ops $.Values.roleGroupBindings.sec | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "dev" ( concat $.Values.roleGroupBindings.dev $.Values.roleGroupBindings.admin | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "dev" ( concat $.Values.roleGroupBindings.dev $.Values.roleGroupBindings.sec | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "dev" ( concat $.Values.roleGroupBindings.dev $.Values.roleGroupBindings.ops | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "viewer" ( concat $.Values.roleGroupBindings.viewer $.Values.roleGroupBindings.admin | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "viewer" ( concat $.Values.roleGroupBindings.viewer $.Values.roleGroupBindings.ops | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "viewer" ( concat $.Values.roleGroupBindings.viewer $.Values.roleGroupBindings.sec | uniq | sortAlpha ) }}
{{- $_ := set $.Values.roleGroupBindings "viewer" ( concat $.Values.roleGroupBindings.viewer $.Values.roleGroupBindings.dev | uniq | sortAlpha ) }}
{{- range $role := $roles }}
# Binding: Roles[{{ $role | quote }}] = {{ index $.Values.roleGroupBindings $role | join ", " }}
{{- end }}

{{- /*
Create "ClusterRoleBinding" & "RoleBinding"
*/}}
{{- range $role := $roles }}
{{- with ( index $.Values.roleGroupBindings $role ) }}
{{- if not ( empty . ) }}

{{- /*
Create "ClusterRoleBinding"
*/}}
{{- if has $role $.Values.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "helm.groupPrefix" $ }}{{ include "helm.fullname" $ }}:{{ $role }}"
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/role: {{ $role | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "helm.groupPrefix" $ }}{{ include "helm.fullname" $ }}:{{ $role }}"
subjects:
{{- range $group := . }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ include "helm.groupPrefix" $ }}{{ . }}"
{{- end }}
{{- end }}

{{- /*
Create "RoleBinding"
*/}}
{{- if has $role $.Values.namespacedRoles }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "helm.groupPrefix" $ }}{{ include "helm.fullname" $ }}:{{ $role }}"
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
    kubernetes.io/service-account.namespace: {{ $.Release.Namespace | quote }}
    org.ulagbulag.io/role: {{ $role | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "helm.groupPrefix" $ }}{{ include "helm.fullname" $ }}:{{ $role }}"
subjects:
{{- range $group := . }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ include "helm.groupPrefix" $ }}{{ . }}"
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
