# Copyright (c) 2025 Ho Kim (ho.kim@ulagbulag.io). All rights reserved.
# Use of this source code is governed by a GPL-3-style license that can be
# found in the LICENSE file.

{{- $package := .Release.Name }}
{{- $version := .Release.Version }}

# Be ready for building
FROM "{{ .Values.builder.image.repo }}:{{ .Values.builder.image.tag }}-{{ .Values.debian.image.tag }}" AS builder

# Install dependencies
RUN apt-get update && apt-get install -y \
        build-essential \
        clang \
        cmake \
        protobuf-compiler \
    # Switch channel
    && rustup default {{ .Values.rust.channel | quote }} \
    # Cleanup
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

# Load source files
ADD . /src
WORKDIR /src

# Build it!
ENV CSI_PROTO_URL={{ printf "%s/%s/%s/refs/heads/%s/csi.proto"
    .Values.csi.baseUrl
    .Values.csi.owner
    .Values.csi.name
    .Values.csi.revision
}}
RUN \
    # Cache build outputs
    --mount=type=cache,target=/src/target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    # Create an output directory
    mkdir /out \
    # Fix version
    && sed -i 's/^\(version \+= \+\"\)[0-9a-z\.-]\+\"/\1{{ $version }}\"/g' ./Cargo.toml \
    # Build
    && cargo build \
        --package 'data-pond' \
        --profile 'release' \
    && find ./target/release/ -maxdepth 1 -type f -perm -a=x -print0 | xargs -0 -I {} mv {} /out

# Be ready for serving
FROM "{{ .Values.debian.image.repo }}:{{ .Values.debian.image.tag }}" AS server

# Install dependencies
RUN apt-get update && apt-get install -y \
        btrfs-progs \
        iproute2 \
        jq \
        kmod \
        lvm2 \
        nvme-cli \
    # Cleanup
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

# Create an user
RUN groupadd --gid "2000" "user" \
    && useradd --uid "2000" --gid "2000" \
        --shell "/bin/bash" --non-unique "user"

# Copy executable files
ADD ./LICENSE "/usr/share/licenses/{{ $package }}/LICENSE"
ADD ./bin/* /usr/local/bin/
COPY --from=builder /out/* /usr/local/bin/

# Mark as executable
CMD [ "./entrypoint.sh" ]
ENTRYPOINT [ "/usr/bin/env" ]
USER user
WORKDIR /usr/local/bin/
