{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "Desktop" }}

---
apiVersion: org.ulagbulag.io/v1alpha1
kind: SessionProfile
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  features:
    desktopEnvironment: true
    devicePassthrough: true
    hostAudio: true
    hostDisplay: true
    hostUdev: true
  persistence:
    enabled: true
  services:
    novnc:
      enabled: true
    ssh:
      enabled: false
    x11vnc:
      enabled: true
  session:
{{- .session | default dict | toYaml | nindent 4 }}
  volumes:
    home:
      type: LocalShared

    public:
      enabled: false
    static:
      enabled: false

{{- end }}
{{- end }}
