{{- if .Values.features.kueue.enabled }}
{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "Kueue" -}}

---
apiVersion: org.ulagbulag.io/v1alpha1
kind: SessionProfile
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  features: {}
  mode: None
  persistence:
    enabled: true
  services: {}
  volumes:
    home:
      type: LocalShared

    public:
      enabled: {{ $.Values.volumes.public.enabled }}
    static:
      enabled: {{ $.Values.volumes.static.enabled }}

{{- end }}
{{- end }}
{{- end }}
