{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "Notebook" }}

---
apiVersion: org.ulagbulag.io/v1alpha1
kind: SessionProfile
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  features:
    audio: false
    desktopEnvironment: false
    devicePassthrough: true
    hostAudio: false
    hostDisplay: false
    hostUdev: true
  persistence:
    enabled: true
  services:
    notebook:
      enabled: true
      image:
{{- .image | default dict | toYaml | nindent 8 }}
    novnc:
      enabled: false
    rdp:
      enabled: false
    ssh:
      enabled: false
    x11vnc:
      enabled: false
  volumes:
    home:
      type: LocalOwned
    vm:
      type: LocalOwned

{{- end }}
{{- end }}
