{{- if .Values.features.nvidiaTriton.enabled }}
{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "NvidiaTriton" }}

---
apiVersion: org.ulagbulag.io/v1alpha1
kind: SessionProfile
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  externalServices:
    nvidiaTriton:
      image:
{{- .image | default dict | toYaml | nindent 8 }}
  features:
    data: true
  mode: NvidiaTriton
  persistence:
    enabled: true
  services: {}
  volumes:
    home:
      type: LocalShared

    public:
      enabled: false
    static:
      enabled: false

{{- end }}
{{- end }}
{{- end }}
