{{- if .Values.features.ollama.enabled }}
{{- range $_ := .Values.profiles | default list }}
{{- if eq .kind "Ollama" }}

---
apiVersion: org.ulagbulag.io/v1alpha1
kind: SessionProfile
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
{{- include "helm.labels" $ | nindent 4 }}
spec:
  externalServices:
    ollama:
      image:
{{- .image | default dict | toYaml | nindent 8 }}
  features: {}
  mode: Ollama
  persistence:
    enabled: true
  services: {}
  volumes:
    home:
      type: LocalShared

    public:
      enabled: false
    static:
      enabled: false

{{- end }}
{{- end }}
{{- end }}
