---
# Prefetched models
models:
  defaultAccessControlProfile: public # Options: [private, public]
  # Pull official Ollama library models
  # - Library: https://ollama.com/library
  pull:
    - name: deepseek-r1:70b
    - name: exaone3.5:32b
    - name: exaone-deep:32b
    - name: exaone-deep:32b-fp16
    - name: gemma3:27b
    - name: gemma3:27b-it-fp16
    - name: llama3.2-vision:90b
    - name: llama3.3:70b
    - name: llama4:scout
    - name: openthinker:32b
    - name: r1-1776:70b
    - name: deepseek-r1:8b-0528-qwen3-fp16

# -- Affinity for pod assignment
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/kiss
              operator: In
              values:
                - Compute

image:
  repo: quay.io/ulagbulag/openark
  tag: ""
  pullPolicy: Always
